version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: Israel
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: Israel
