services:
  admin-server:
    build:
      context: ./admin-server
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - my-network
  web-socket-reactive:
    build:
      context: ./web-socket-reactive
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s  # preventing multiple services from trying to bind to the same port simultaneously
    depends_on:
      - admin-server
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "DELAY_SERVICE_HOST=delay-service-reactive"
    networks:
      - my-network
  delay-service-reactive:
    build:
      context: ./delay-service-reactive
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s  # preventing multiple services from trying to bind to the same port simultaneously
    depends_on:
      - admin-server
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - my-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - prometheus
networks:
  my-network:
    driver: bridge