name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    permissions: write-all #for dependabot auto PR - create a test report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build by Maven
        run: mvn clean install -DskipTests=true
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
##       Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: "docker compose up"
        run: docker compose -f docker-compose.yml up -d --wait
      - name: "Wait 10 seconds for docker container will register in Eureka Server"
        run: sleep 10 # wait until docker container started (in second)
      - name: "run integration tests"
        run: mvn test
      - name: websocket-reactive integration Test Report
        uses: dorny/test-reporter@v1.9.1 #{owner}/{repository}@{ref}
        if: (success() || failure())
        #        if: github.actor != 'dependabot[bot]' && (success() || failure())
        with:
          name: websocket-reactive Tests - converter-service #for analysis tests report
          path: web-socket-reactive/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
        # Now you can pass ${{ steps.buildnumber.outputs.build_number }} to the next steps.
      - name: Another step as an example
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: ${{ steps.buildnumber.outputs.build_number }}
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
